# Generated by Django 3.0.7 on 2023-10-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
