# Generated by Django 3.0.7 on 2023-10-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231008_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagramlink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinterestlink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitterlink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='websitelink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtubelink',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
